# Managing Sensitive Information with Secrets

. Create the authorization-secrets project.
+
[source,bash,role="execute"]
----
oc new-project authorization-secrets
Now using project "authorization-secrets" on server "https://api.cluster-754d.sandbox478.opentlc.com:6443".
...output omitted...
----

. Create a secret with the credentials and connection information to access a MySQL database.
+
[source,bash,role="execute"]
----
oc create secret generic mysql \
--from-literal user=myuser --from-literal password=redhat123 \
--from-literal database=test_secrets --from-literal hostname=mysql
----

. Deploy a database and add the secret for user and database configuration.

.. Try to deploy an ephemeral database server. This should fail because the MySQL image needs environment variables for its initial configuration. The values for these variables cannot be assigned from a secret using the oc new-app command.
+
[source,bash,role="execute"]
----
oc new-app --name mysql \
--image registry.redhat.io/rhel8/mysql-80:1

...output omitted...
--> Creating resources ...
    imagestream.image.openshift.io "mysql" created
    deployment.apps "mysql" created
    service "mysql" created
--> Success
...output omitted..
----

.. Run the oc get pods command with the -w option to retrieve the status of the deployment in real time. Notice how the database pod is in a failed state. Press Ctrl+C to exit the command.
+
[source,bash,role="execute"]
----
oc get pods -w

NAME                     READY   STATUS             RESTARTS      AGE
mysql-7b58b9b68b-2qswd   0/1     CrashLoopBackOff   2 (14s ago)   32s
mysql-7b58b9b68b-2qswd   0/1     Error              3 (23s ago)   41s
mysql-7b58b9b68b-2qswd   0/1     CrashLoopBackOff   3 (14s ago)   55s
mysql-7b58b9b68b-2qswd   0/1     Error              4 (41s ago)   82s
----

.. Use the mysql secret to initialize environment variables on the mysql deployment. The deployment needs the MYSQL_USER, MYSQL_PASSWORD, and MYSQL_DATABASE environment variables for a successful initialization. The secret has the user, password, and database keys that can be assigned to the deployment as environment variables, adding the prefix MYSQL_.
+
[source,bash,role="execute"]
----
oc set env deployment/mysql --from secret/mysql \
--prefix MYSQL_
deployment.apps/mysql updated
----

.. To demonstrate how a secret can be mounted as a volume, mount the mysql secret to the /run/secrets/mysql directory within the
+
[source,bash,role="execute"]
----
 oc set volume deployment/mysql --add --type secret \
 --mount-path /run/secrets/mysql --secret-name mysql
info: Generated volume name: volume-vwzpr
deployment.apps/mysql volume updated
----

.. Modifying the deployment using the oc set env command or the oc set volume command triggers a new application deployment. Verify that the mysql application deploys successfully after the modifications.
+
[source,bash,role="execute"]
----
oc get pods
NAME                     READY   STATUS    RESTARTS   AGE
mysql-7cd7499d66-gm2rh   1/1     Running   0          21s
----

. Verify that the database now authenticates using the environment variables initialized from the mysql secret.

.. Open a remote shell session to the mysql pod in the Running state.
+
[source,bash,role="execute"]
----
oc rsh mysql-84895b7b88-qn2ps
sh-4.4$
----

.. Start a MySQL session to verify that the environment variables initialized by the mysql secret were used to configure the mysql application.
+
[source,bash,role="execute"]
----
sh-4.4$ mysql -u myuser --password=redhat123 test_secrets -e 'show databases;'
mysql: [Warning] Using a password on the command line interface can be insecure.
+--------------------+
| Database           |
+--------------------+
| information_schema |
| test_secrets       |
+--------------------+
----

.. List mount points in the pod containing the mysql pattern. Notice that the mount point is backed by a temporary file system (tmpfs). This is true for all secrets that are mounted as volumes.
+
[source,bash,role="execute"]
----
sh-4.4$ df -h | grep mysql
tmpfs            15G   16K   15G   1% /run/secrets/mysql
----

.. Examine the files mounted at the /run/secrets/mysql mount point. Each file matches a key name in the secret, and the content of each file is the value of the associated key.
+
[source,bash,role="execute"]
----
sh-4.4$ for FILE in $(ls /run/secrets/mysql)
do
echo "${FILE}: $(cat /run/secrets/mysql/${FILE})"
done
database: test_secrets
hostname: mysql
password: redhat123
user: myuser
----

.. Close the remote shell session to continue from your workstation machine.
+
[source,bash,role="execute"]
----
sh-4.4$ exit
exit
[student@workstation ~]$
----

. Create a new application that uses the MySQL database.

.. Create a new application using the redhattraining/famous-quotes image from Quay.io.
+
[source,bash,role="execute"]
----
oc new-app --name quotes \
>   --image quay.io/redhattraining/famous-quotes:2.1
--> Found container image 7ff1a7b (7 months old) from quay.io for "quay.io/redhattraining/famous-quotes:latest"
...output omitted...
--> Creating resources ...
    imagestream.image.openshift.io "quotes" created
    deployment.apps "quotes" created
    service "quotes" created
--> Success
...output omitted...
----

.. Verify the status of the quotes application pod. The pod displays an error because it cannot connect to the database. This might take a while to display in the output. Press Ctrl+C to exit the command.
+
[source,bash,role="execute"]
----
oc get pods -l deployment=quotes -w
NAME                      READY   STATUS             RESTARTS      AGE
quotes-66b987df5d-7nnjf   0/1     CrashLoopBackOff   4 (25s ago)   2m7s
----

. The quotes application requires several environment variables. The mysql secret can initialize environment variables for the quotes application by adding the QUOTES_ prefix.

.. Use the mysql secret to initialize the following environment variables that the quotes application needs to connect to the database: QUOTES_USER, QUOTES_PASSWORD, QUOTES_DATABASE, and QUOTES_HOSTNAME, which correspond to the user, password, database, and hostname keys of the mysql secret.
+
[source,bash,role="execute"]
----
oc set env deployment/quotes --from secret/mysql \
--prefix QUOTES_
deployment.apps/quotes updated
----

.. Wait until the quotes application pod redeploys. The older pods terminate automatically.
+
[source,bash,role="execute"]
----
oc get pods -l deployment=quotes
NAME                      READY   STATUS    RESTARTS   AGE
quotes-8595f8bfcf-96rmn   1/1     Running   0          19s
----

. Verify that the quotes pod successfully connects to the database and that the application displays a list of quotes.
.. Examine the pod logs using the oc logs command. The logs indicate a successful database connection.
+
[source,bash,role="execute"]
----
oc logs  -f quotes-8595f8bfcf-96rmn | head -n2
2022/04/23 15:56:11 Connecting to the database: myuser:redhat123@tcp(mysql:3306)/test_secrets
2022/04/23 15:56:11 Database connection OK
----

.. Expose the quotes service so that it can be accessed from outside the cluster.
+
[source,bash,role="execute"]
----
oc expose service quotes
route.route.openshift.io/quotes exposed
----

.. Verify the application host name.
+
[source,bash,role="execute"]
----
oc get route
NAME     HOST/PORT                                                                      PATH   SERVICES   PORT       TERMINATION   WILDCARD
quotes   quotes-authorization-secrets.apps.cluster-754d.sandbox478.opentlc.com          quotes     8000-tcp                 None
----

.. Verify that the variables are properly set in the application by accessing the env REST API entry point.
+
[source,bash,role="execute"]
----
curl -s http://quotes-authorization-secrets.apps.cluster-754d.sandbox478.opentlc.com/env | grep QUOTES_                                              ─╯
                <li>QUOTES_USER: myuser </li>
                <li>QUOTES_PASSWORD: redhat123 </li>
                <li>QUOTES_DATABASE: test_secrets</li>
                <li>QUOTES_HOST: mysql</li>
----

.. Access the application status REST API entry point to test the database connection.
+
[source,bash,role="execute"]
----
curl -s http://quotes-authorization-secrets.apps.cluster-754d.sandbox478.opentlc.com/status
Database connection OK
----

.. Test application functionality by accessing the random REST API entry point.
+
[source,bash,role="execute"]
----
curl -s http://quotes-authorization-secrets.apps.cluster-754d.sandbox478.opentlc.com/random
1: When words fail, music speaks.
- William Shakespeare
----

. Remove the authorization-secrets project.

+
[source,bash,role="execute"]
----
oc delete project authorization-secrets
project.project.openshift.io "authorization-secrets" deleted
----